### ISSUE TITLE
Package ‘mhde’ was removed from the CRAN repository

### ISSUE THREAD

**Issue by strboul** [alastairrushworth/normality#1]
The package can still be accessed from the archive but it would be better if it could be replaced with an alternative.
https://cran.r-project.org/web/packages/mhde/

**Comment by alastairrushworth** [comment]
Thanks @strboul I've pushed an update to fix this.  I've added some of the bits of archived code from mhde so that the test is still accessible.  I'll reinstate the dependency if the package comes out of archiving at some point.
